apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  namespace: petclinic
spec:
  type: LoadBalancer
  selector:
    app: spring-petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
